### ISSUE TITLE
Can not add the extention

### ISSUE THREAD

**Issue by vinokurig** [theia-ide/theia-json-extension#3]
Adding reference to this extension in `package.json` causes errors:
```
[2018-05-16T06:19:06.338Z] ERROR: Theia/10081 on desktop: (logger=root)
    Error: webpack failed with the exit code 2
        at ChildProcess.<anonymous> (/home/ivinokur/projects/theia/dev-packages/application-manager/lib/application-process.js:59:28)
        at emitTwo (events.js:125:13)
        at ChildProcess.emit (events.js:213:7)
        at maybeClose (internal/child_process.js:927:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
     []
```

**Comment by svenefftinge** [comment]
Sorry for responding so late. It works with the usual version range problems.
I.e. if you use the `next` tag and the `next` tag of `@theia/core` it should work.
Please reopen if the issue persists.
